// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').controller('BroadcastCtrl', function($scope) {
    return $scope.loading = false;
  });

}).call(this);
