// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('newBetaApp').controller('DownloadCtrl', [
    '$scope', 'downloadUrl', function($scope, downloadUrl) {
      return $scope.url = downloadUrl;
    }
  ]);

}).call(this);
