// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').controller('LineCtrl', [
  '$scope', 'lineStats', 'Line', 'filter', function($scope, lineStats, Line, filter) {
    var scope;
    scope = $scope;
    scope.dragging;
    scope.selectedLine;
    scope.lines = {};
    scope.includedGames = filter.included;
    $scope.loading = true;
    lineStats.then(function(response) {
      lineStats = response;
      $scope.players = lineStats.getPlayers();
      return $scope.loading = false;
    });
    scope.setDragging = function(player) {
      return scope.dragging = player;
    };
    scope.addLine = function() {
      var line;
      line = new Line;
      scope.lines[line.id] = line;
      return scope.selectedLine = line;
    };
    scope.removeLine = function(line) {
      return delete scope.lines[line.id];
    };
    scope.addPlayerToSelected = function(player) {
      return scope.selectedLine.addPlayer(player);
    };
    scope.selectLine = function(line) {
      return scope.selectedLine = line;
    };
    scope._contains = _.contains;
    scope.addLine();
    return scope.$watchCollection('includedGames', function(update, old) {
      if (update && lineStats.getStats) {
        return _(scope.lines).each(function(line) {
          return line.updateStats();
        });
      }
    });
  }
]);
