// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').controller('MainCtrl', function($rootScope, filter) {
    return $rootScope.getSharedData = function() {
      var data;
      data = {};
      data.gameIds = _.pluck(filter.included, 'gameId');
      return data;
    };
  });

}).call(this);
