// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').controller('PlayerCtrl', [
    '$scope', '$routeParams', '$q', 'allGames', 'playerExtensionStats', 'filter', 'team', function($scope, $routeParams, $q, allGames, playerExtensionStats, filter, team) {
      var init, players, scope;
      scope = $scope;
      scope.loading = true;
      scope.console = console;
      players = null;
      scope.playerName = decodeURI($routeParams.playerNameUri);
      $q.all([allGames, playerExtensionStats]).then(function(responses) {
        allGames = responses[0];
        playerExtensionStats = responses[1];
        init();
        return scope.loading = false;
      });
      return init = function() {
        filter.includeAll();
        scope.included = filter.included;
        playerExtensionStats.setPlayer(scope.playerName);
        return scope.$watchCollection('included', function() {
          playerExtensionStats.setGames(scope.included);
          return scope.targetStats = playerExtensionStats.getTargetMap();
        });
      };
    }
  ]);

}).call(this);
