// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Service: lineView', function() {
    var lineView;
    beforeEach(module('newBetaApp'));
    lineView = {};
    beforeEach(inject(function(_lineView_) {
      return lineView = _lineView_;
    }));
    return it('should do something', function() {
      return expect(!!lineView).toBe(true);
    });
  });

}).call(this);
