// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Service: nameLookups', function() {
    var nameLookups;
    beforeEach(module('newBetaApp'));
    nameLookups = {};
    beforeEach(inject(function(_nameLookups_) {
      return nameLookups = _nameLookups_;
    }));
    return it('should do something', function() {
      return expect(!!nameLookups).toBe(true);
    });
  });

}).call(this);
