// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  describe('Service: savedState', function() {
    var savedState;
    beforeEach(module('newBetaApp'));
    savedState = {};
    beforeEach(inject(function(_savedState_) {
      return savedState = _savedState_;
    }));
    return it('should do something', function() {
      return expect(!!savedState).toBe(true);
    });
  });

}).call(this);
