// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Service: utils', function() {
    var utils;
    beforeEach(module('newBetaApp'));
    utils = {};
    beforeEach(inject(function(_utils_) {
      return utils = _utils_;
    }));
    return it('should do something', function() {
      return expect(!!utils).toBe(true);
    });
  });

}).call(this);
