// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  describe('Filter: statSort', function() {
    var statSort;
    beforeEach(module('newBetaApp'));
    statSort = {};
    beforeEach(inject(function($filter) {
      return statSort = $filter('statSort');
    }));
    return it('should return the input prefixed with "statSort filter:"', function() {
      var text;
      text = 'angularjs';
      return expect(statSort(text)).toBe('statSort filter: ' + text);
    });
  });

}).call(this);
