// Generated by CoffeeScript 1.7.1
'use strict';
describe('Directive: footer', function() {
  var scope;
  beforeEach(module('newBetaApp'));
  scope = {};
  beforeEach(inject(function($controller, $rootScope) {
    return scope = $rootScope.$new();
  }));
  return it('should make hidden element visible', inject(function($compile) {
    var element;
    element = angular.element('<footer></footer>');
    element = $compile(element)(scope);
    return expect(element.text()).toBe('this is the footer directive');
  }));
});
