// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('Controller: StateCtrl', function() {
    var StateCtrl, scope;
    beforeEach(module('newBetaApp'));
    StateCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return StateCtrl = $controller('StateCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);
