// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').filter('eventImageUrl', function() {
    return function(event) {
      var url;
      url = 'images/cuties/';
      switch (event.action) {
        case 'Catch':
          url += 'big_smile.png';
          break;
        case 'Drop':
          url += 'eyes_droped.png';
          break;
        case 'Throwaway':
          url += event.type === 'Offense' ? 'shame.png' : 'exciting.png';
          break;
        case 'Stall':
          url += 'shame.png';
          break;
        case 'MiscPenalty':
          url += 'shame.png';
          break;
        case 'D':
          url += 'electric_shock.png';
          break;
        case 'Pull':
          url += 'nothing.png';
          break;
        case 'PullOb':
          url += 'what.png';
          break;
        case 'Goal':
          url += event.type === 'Offense' ? 'super_man.png' : 'cry.png';
          break;
        case 'Callahan':
          url += 'victory.png';
          break;
        case 'EndOfFirstQuarter':
          url += 'stopwatch1.png';
          break;
        case 'EndOfThirdQuarter':
          url += 'stopwatch1.png';
          break;
        case 'EndOfFourthQuarter':
          url += 'stopwatch1.png';
          break;
        case 'EndOfOvertime':
          url += 'stopwatch1.png';
          break;
        case 'Halftime':
          url += 'stopwatch1.png';
          break;
        case 'GameOver':
          url += 'finishflag.png';
          break;
        case 'Timeout':
          url += 'stopwatch1.png';
          break;
        default:
          url += 'money.png';
      }
      return url;
    };
  });

}).call(this);
