'use strict'

angular.module('newBetaApp')
  .filter 'eventImageUrl', () ->
    (event) ->
      url = 'images/cuties/'
      switch event.action
        when 'Catch'
          url += 'big_smile.png'
        when 'Drop' 
          url += 'eyes_droped.png'
        when 'Throwaway'
          url += if event.type == 'Offense' then 'shame.png' else 'exciting.png'
        when 'Stall'
          url += 'shame.png'
        when 'MiscPenalty'
          url += 'shame.png'
        when 'D' 
          url += 'electric_shock.png'
        when 'Pull' 
          url += 'nothing.png'
        when 'PullOb' 
          url += 'what.png'
        when 'Goal'
          url += if event.type == 'Offense' then 'super_man.png' else 'cry.png'
        when 'Callahan'
          url += 'victory.png'
        when 'EndOfFirstQuarter'
          url += 'stopwatch1.png'
        when 'EndOfThirdQuarter'
          url += 'stopwatch1.png'
        when 'EndOfFourthQuarter'
          url += 'stopwatch1.png'
        when 'EndOfOvertime'
          url += 'stopwatch1.png'
        when 'Halftime'
          url += 'stopwatch1.png'
        when 'GameOver'
          url += 'finishflag.png'
        when 'Timeout'
          url += 'stopwatch1.png'
        else
          url += 'money.png'
      url
