'use strict'

angular.module('newBetaApp')
  .filter 'eventImageUrl', () ->
    (event) ->
      url = 'images/events/'
      switch event.action
        when 'Catch'
          url += 'pass.png'
        when 'Drop' 
          url += 'drop.png'
        when 'Throwaway'
          url += 'throwaway.png'
        when 'Stall'
          url += 'stall.png'
        when 'MiscPenalty'
          url += 'penalty.png'
        when 'D' 
          url += 'd.png'
        when 'Pull' 
          url += 'pull.png'
        when 'PullOb' 
          url += 'pull-ob.png'
        when 'Goal'
          url += if event.type == 'Offense' then 'goal.png' else 'goal-opponent.png'
        when 'Callahan'
          url += if event.type == 'Offense' then 'callahan-opponent.png' else 'callahan.png'
        when 'EndOfFirstQuarter'
          url += 'period-end.png'
        when 'EndOfThirdQuarter'
          url += 'period-end.png'
        when 'EndOfFourthQuarter'
          url += 'period-end.png'
        when 'EndOfOvertime'
          url += 'period-end.png'
        when 'Halftime'
          url += 'period-end.png'
        when 'GameOver'
          url += 'game-over.png'
        when 'Timeout'
          url += 'period-end.png'
        else
          url += 'game-over.png'
      url
