// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').filter('hundredths', function() {
  return function(input) {
    if (_(input).isNaN()) {
      return '?';
    } else if (_(input).isNumber()) {
      return input.toFixed(2).replace(/(\.00$)|(0*$)/, '');
    } else {
      return 'NA';
    }
  };
});
