// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').filter('statSort', function($rootScope) {
    return function(input, type, reverse) {
      var copy, factor;
      if (!input) {
        return Math.random();
      }
      copy = _.clone(input);
      factor = reverse ? 1 : -1;
      return copy.sort(function(playerA, playerB) {
        var diff, nameToSortA, nameToSortB, statA, statB;
        if (type !== 'name') {
          statA = _.isNaN(playerA.stats[type]) ? -9999999 : playerA.stats[type];
          statB = _.isNaN(playerB.stats[type]) ? -9999999 : playerB.stats[type];
          diff = statA - statB;
          return diff * factor;
        } else {
          nameToSortA = $rootScope.getName(playerA.name, 'last') || $rootScope.getName(playerA.name, 'first');
          nameToSortB = $rootScope.getName(playerB.name, 'last') || $rootScope.getName(playerB.name, 'first');
          if (nameToSortA < nameToSortB) {
            return factor;
          } else if (nameToSortA > nameToSortB) {
            return factor * -1;
          }
        }
      });
    };
  });

}).call(this);
