// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').filter('statSort', function() {
    return function(input, type, reverse) {
      var copy, factor;
      if (!input) {
        return Math.random();
      }
      copy = _.clone(input);
      factor = reverse ? 1 : -1;
      return copy.sort(function(playerA, playerB) {
        var diff;
        if (type !== 'name') {
          diff = playerA.stats[type] - playerB.stats[type];
          return diff * factor;
        } else {
          if (playerA.name < playerB.name) {
            return factor;
          } else if (playerA.name > playerB.name) {
            return factor * -1;
          }
        }
      });
    };
  });

}).call(this);
