// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').filter('statSort', function($rootScope) {
    return function(input, type, reverse) {
      var copy, factor;
      if (!input) {
        return Math.random();
      }
      copy = _.clone(input);
      factor = reverse ? 1 : -1;
      return copy.sort(function(playerA, playerB) {
        var diff, nameToSortA, nameToSortB;
        if (type !== 'name') {
          diff = playerA.stats[type] - playerB.stats[type];
          return diff * factor;
        } else {
          nameToSortA = $rootScope.getName(playerA.name, 'last') || $rootScope.getName(playerA.name, 'first');
          nameToSortB = $rootScope.getName(playerB.name, 'last') || $rootScope.getName(playerB.name, 'first');
          if (nameToSortA < nameToSortB) {
            return factor;
          } else if (nameToSortA > nameToSortB) {
            return factor * -1;
          }
        }
      });
    };
  });

}).call(this);
