// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').factory('broadcastApi', function($http, $routeParams) {
    var baseUrl;
    baseUrl = "http://127.0.0.1:8080/broadcast";
    return {
      getEvents: function() {
        return $http.get("" + baseUrl + "/" + $routeParams.teamId + "/events");
      }
    };
  });

}).call(this);
