// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').factory('downloadUrl', [
    '$routeParams', 'api', function($routeParams, api) {
      return api.urlForStatsExportFileDownload($routeParams.teamId, null);
    }
  ]);

}).call(this);
