// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').factory('gameStats', [
    '$q', 'allGames', 'playerStats', function($q, allGames, playerStats) {
      var api, deferred;
      deferred = $q.defer();
      $q.all([allGames, playerStats]).then(function(response) {
        allGames = response[0];
        playerStats = response[1];
        return deferred.resolve(api);
      });
      api = {};
      api.getFor = function(game) {
        var leaders, players, relevant, results;
        results = {};
        playerStats.setGames([game]);
        players = playerStats.getAll();
        relevant = _.where(allGames, {
          opponentName: game.opponentName
        });
        if (!_(relevant).isArray()) {
          relevant = [relevant];
        }
        results.record = _.countBy(relevant, function(game) {
          if (game.ours > game.theirs) {
            return 'wins';
          } else {
            return 'losses';
          }
        });
        _(results.record).defaults({
          wins: 0,
          losses: 0
        });
        leaders = {};
        _(['goals', 'assists', 'ds', 'throwaways', 'plusMinus']).each(function(type) {
          return leaders[type] = _.max(players, function(player) {
            return player.stats[type];
          });
        });
        results.leaders = leaders;
        return results;
      };
      return deferred.promise;
    }
  ]);

}).call(this);
