// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('newBetaApp').factory('LineView', function(Line) {
    var LineView;
    LineView = (function() {
      function LineView() {
        this.selectedAddPlayer = __bind(this.selectedAddPlayer, this);
        this.selectedLine = null;
        this.lines = {};
      }

      LineView.prototype.addLine = function(silent) {
        var line;
        line = new Line;
        this.lines[line.id] = line;
        if (!silent) {
          this.selectedLine = line;
        }
        return line;
      };

      LineView.prototype.removeLine = function(line) {
        return delete this.lines[line.id];
      };

      LineView.prototype.selectLine = function(line) {
        return this.selectedLine = line;
      };

      LineView.prototype.isSelectedLine = function(line) {
        return this.selectedLine === line;
      };

      LineView.prototype.selectedAddPlayer = function(player) {
        return this.selectedLine.addPlayers(player);
      };

      LineView.prototype.numberOfLines = function() {
        return _.keys(this.lines).length;
      };

      LineView.prototype.updateStats = function() {
        return _.each(this.lines, function(line) {
          return line.updateStats();
        });
      };

      return LineView;

    })();
    return LineView;
  });

}).call(this);
