// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('newBetaApp').factory('LineView', function(Line) {
    var LineView;
    LineView = (function() {
      function LineView() {
        this.selectedAddPlayer = __bind(this.selectedAddPlayer, this);
        this.selectedLine = null;
        this.lines = {};
      }

      LineView.prototype.addLine = function() {
        var line;
        line = new Line;
        return this.lines[line.id] = this.selectedLine = line;
      };

      LineView.prototype.removeLine = function(line) {
        return delete this.lines[line.id];
      };

      LineView.prototype.selectLine = function(line) {
        return this.selectedLine = line;
      };

      LineView.prototype.selectedAddPlayer = function(player) {
        return this.selectedLine.addPlayer(player);
      };

      LineView.prototype.numberOfLines = function() {
        return _.keys(this.lines).length;
      };

      return LineView;

    })();
    return LineView;
  });

}).call(this);
