// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('newBetaApp').factory('Line', [
    'lineStats', function(lineStats) {
      var Line, lineNum;
      lineStats.then(function(response) {
        return lineStats = response;
      });
      lineNum = 0;
      return Line = (function() {
        function Line() {
          this.addPlayer = __bind(this.addPlayer, this);
          this.stats = {};
          this.id = ++lineNum;
          this.players = [];
        }

        Line.prototype.addPlayer = function(player) {
          if (this.players.length < 7) {
            this.players = _.union(this.players, [player]);
            return this.updateStats();
          }
        };

        Line.prototype.removePlayer = function(player) {
          this.players = _.without(this.players, player);
          return this.updateStats();
        };

        Line.prototype.updateStats = function() {
          return this.stats = lineStats.getStats(this.players);
        };

        return Line;

      })();
    }
  ]);

}).call(this);
