// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('newBetaApp').factory('Line', [
    'lineStats', function(lineStats) {
      var Line, lineNum;
      lineStats.then(function(response) {
        return lineStats = response;
      });
      lineNum = 0;
      return Line = (function() {
        Line.prototype.getPlayers = function() {
          return this.players;
        };

        function Line() {
          this.addPlayers = __bind(this.addPlayers, this);
          this.stats = {};
          this.id = ++lineNum;
          this.players = [];
        }

        Line.prototype.addPlayers = function(players) {
          if (this.players.length < 7) {
            if (!_(players).isArray()) {
              players = [players];
            }
            this.players = _.union(this.players, players);
            return this.updateStats();
          }
        };

        Line.prototype.removePlayer = function(player) {
          this.players = _.without(this.players, player);
          return this.updateStats();
        };

        Line.prototype.updateStats = function() {
          return this.stats = lineStats.getStats(this.players);
        };

        return Line;

      })();
    }
  ]);

}).call(this);
