// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').factory('playerExtensionStats', [
    '$q', 'allGames', function($q, allGames) {
      var api, consideredGames, deferred, playerName;
      playerName = '';
      consideredGames = [];
      api = {
        setGames: function(games) {
          return consideredGames = games;
        },
        setPlayer: function(name) {
          return playerName = name;
        },
        getTargetMap: function() {
          var actions, children, playersThrows;
          children = [];
          playersThrows = [];
          _.each(consideredGames, function(game) {
            return _.each(game.points, function(point) {
              return _.each(point.events, function(event) {
                if (event.passer === playerName) {
                  return playersThrows.push(event);
                }
              });
            });
          });
          actions = _.groupBy(playersThrows, 'action');
          _.each(actions, function(events, action) {
            var receivers;
            receivers = _.countBy(events, function(event) {
              return event.receiver || 'The Other Team';
            });
            return _.each(receivers, function(count, player) {
              return children.push({
                actionType: action,
                receiver: player,
                value: count
              });
            });
          });
          return {
            children: children
          };
        }
      };
      allGames.then(function(response) {
        allGames = response;
        return deferred.resolve(api);
      });
      deferred = $q.defer();
      return deferred.promise;
    }
  ]);

}).call(this);
