// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('newBetaApp').factory('relocate', [
    '$location', '$routeParams', function($location, $routeParams) {
      var base;
      base = $routeParams.teamId + '/';
      return {
        goTo: function(route, query) {
          return $location.path(base + route + '/' + decodeURIComponent(query));
        }
      };
    }
  ]);

}).call(this);
