// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').factory('savedState', function() {
    var data;
    data = {};
    return {
      getOnce: function() {
        var temp;
        temp = data;
        data = {};
        return temp;
      },
      set: function(newData) {
        return _.extend(data, newData);
      }
    };
  });

}).call(this);
