// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').factory('savedState', function() {
    var meaningOfLife;
    meaningOfLife = 42;
    return {
      someMethod: function() {
        return meaningOfLife;
      }
    };
  });

}).call(this);
