// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').factory('utils', function() {
    return {
      objToArr: function(obj, keyName) {
        return _.reduce(obj, function(arr, chunk, key) {
          if (keyName) {
            chunk[keyName] = key;
          }
          arr.push(chunk);
          return arr;
        }, []);
      }
    };
  });

}).call(this);
