// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').directive('actionField', function() {
    return {
      templateUrl: 'includes/partials/field.html',
      restrict: 'E',
      link: function(scope, element, attrs) {}
    };
  });

}).call(this);
