// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').directive('chartKey', function() {
    return {
      templateUrl: 'includes/partials/chart-key.html',
      restrict: 'E',
      scope: {
        colorScheme: '='
      }
    };
  });

}).call(this);
