// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').directive('draggable', [
    '$parse', function($parse) {
      return {
        restrict: 'A',
        link: function(scope, element, attrs) {
          var item, onDrag;
          item = $parse(attrs.item)(scope);
          onDrag = $parse(attrs.onDrag)(scope);
          return element.on('dragstart', function() {
            return onDrag(item);
          });
        }
      };
    }
  ]);

}).call(this);
