// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').directive('droppable', [
  '$parse', function($parse) {
    return {
      restrict: 'A',
      scope: true,
      link: function(scope, element, attrs) {
        var onDrop, onEnter, onLeave;
        onEnter = $parse(attrs.onEnter)(scope);
        onLeave = $parse(attrs.onLeave)(scope);
        onDrop = $parse(attrs.onDrop)(scope);
        element.on('dragenter', function(event) {
          return typeof onEnter === "function" ? onEnter(scope.dragging) : void 0;
        });
        element.on('dragleave', function(event) {
          return typeof onLeave === "function" ? onLeave(scope.dragging) : void 0;
        });
        element.on('drop', function(event) {
          if (typeof onDrop === "function") {
            onDrop(scope.dragging);
          }
          return scope.$digest();
        });
        return element.on('dragover', function(event) {
          if (typeof onOver === "function") {
            onOver(scope.dragging);
          }
          return event.preventDefault();
        });
      }
    };
  }
]);
