// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').directive('explanation', function(calculationExplanations, $sce) {
    return {
      templateUrl: 'includes/partials/explanation.html',
      restrict: 'E',
      replace: true,
      scope: {
        key: '=',
        trigger: '='
      },
      link: function(scope, element, attrs) {
        var description, _ref;
        element.parent().on('mouseenter', function(event) {
          return scope.$apply(function() {
            return scope.showPrompt = !scope.shouldShowToolTip;
          });
        });
        element.parent().on('mouseleave', function() {
          return scope.$apply(function() {
            return scope.showPrompt = false;
          });
        });
        description = (_ref = calculationExplanations[scope.key]) != null ? _ref.explanations[0].description : void 0;
        scope.hasDescription = !!description;
        scope.explanation = $sce.trustAsHtml(description || 'Ask us personally about this one if you\'d like.');
        scope.showTooltip = function() {
          return setTimeout(function() {
            return scope.$apply(function() {
              var $explanationTooltip, documentWidth, elementRightOffset;
              elementRightOffset = $(element).offset().left + 200;
              documentWidth = $(document).width();
              $explanationTooltip = $(element).find('.explanation-tooltip');
              if (documentWidth < elementRightOffset) {
                $explanationTooltip.css('left', -1 * (elementRightOffset - documentWidth));
              }
              scope.shouldShowToolTip = true;
              return scope.showPrompt = false;
            });
          });
        };
        scope.hideTooltip = function() {
          return scope.shouldShowToolTip = false;
        };
        return $(window).on('click', function(event) {
          if (!(scope.shouldShowToolTip === false || event.currentTarget === $(element).find('span.explanation-description')[0])) {
            return scope.$apply(function() {
              return scope.hideTooltip();
            });
          }
        });
      }
    };
  });

}).call(this);
