// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').directive('feedback', [
  '$cookies', function($cookies) {
    return {
      templateUrl: 'includes/partials/feedback.html',
      restrict: 'E',
      link: function(scope, element, attrs) {
        scope.gotMobileWarning = $cookies.iUltimateVisited === 'mobile';
        scope.firstTime = !$cookies.iUltimateVisited;
        scope.submitted = false;
        scope.closeFirstTimeModal = function() {
          scope.firstTime = true;
          $cookies.iUltimateVisited = 'true';
          try {
            $('.modal-backdrop').remove();
            return $('.modal').remove();
          } catch (_error) {}
        };
        return scope.closeMobileWarning = function() {
          scope.gotMobileWarning = true;
          $cookies.iUltimateVisited = 'mobile';
          try {
            $('.modal-backdrop').remove();
            return $('.modal').remove();
          } catch (_error) {}
        };
      }
    };
  }
]);
