// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').directive('feedback', [
    function() {
      return {
        templateUrl: 'includes/partials/feedback.html',
        restrict: 'E',
        link: function(scope, element, attrs) {
          scope.gotMobileWarning = _(document.cookie).contains('mobile');
          scope.firstTime = !_(document.cookie).contains('visited');
          scope.submitted = false;
          scope.closeFirstTimeModal = function() {
            scope.firstTime = false;
            return document.cookie = 'visited=true;max-age=100000000000';
          };
          return scope.closeMobileWarning = function() {
            scope.gotMobileWarning = true;
            return document.cookie = 'mobile-visited=true;max-age=100000000000';
          };
        }
      };
    }
  ]);

}).call(this);
