// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('newBetaApp').directive('fullScreen', function() {
    return {
      template: '<i class="icon-fullscreen">',
      restrict: 'E',
      scope: {
        key: '='
      },
      link: function(scope, element, attrs) {
        return element.on('click', function() {
          var requestFullscreen, targetElement;
          requestFullscreen = element[0].requestFullscreen || element[0].webkitRequestFullScreen || element[0].mozRequestFullScreen || element[0].msRequestFullScreen;
          targetElement = $("[fs-target=" + scope.key + "]")[0];
          return requestFullscreen.call(targetElement);
        });
      }
    };
  });

}).call(this);
