// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').directive('playerStatTable', [
    '$routeParams', 'playerStats', 'filter', function($routeParams, playerStats, filter) {
      return {
        templateUrl: 'includes/partials/playerStatTable.html',
        restrict: 'E',
        scope: {
          playerName: '='
        },
        link: function(scope, element, attrs) {
          var api, init;
          api = null;
          playerStats.then(function(response) {
            api = response;
            return init();
          });
          scope.included = filter.included;
          scope.$watchCollection('included', function() {
            if (api != null) {
              api.setGames(filter.included);
            }
            scope.playerStats = api != null ? api.getAll()[scope.playerName].stats : void 0;
            return scope.teamAverage = api != null ? api.getAverages() : void 0;
          });
          return init = function() {
            api.setGames(scope.included);
            scope.playerStats = api.getAll()[scope.playerName].stats;
            scope.teamAverage = api.getAverages();
            return scope.statTypes = _(scope.playerStats).omit(['timePlayed', 'hungPulls', 'pullHangtime']).keys(scope.playerStats).valueOf().sort();
          };
        }
      };
    }
  ]);

}).call(this);
