// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').directive('rotating', function() {
  return {
    restrict: 'A',
    scope: {
      rotating: '='
    },
    compile: function() {
      return {
        pre: function(scope, element, attrs) {
          element.addClass('rotating');
          return scope.$watch('rotating', function(newVal, oldVal) {
            return element.css('-webkit-transform', 'rotate(' + newVal + 'deg)');
          });
        }
      };
    }
  };
});
