// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('newBetaApp').directive('rotating', function() {
    return {
      restrict: 'A',
      scope: {
        rotating: '='
      },
      compile: function() {
        return {
          pre: function(scope, element, attrs) {
            element.addClass('rotating');
            return scope.$watch('rotating', function(newVal, oldVal) {
              element.css('-webkit-transform', 'rotate(' + newVal + 'deg)');
              element.css('-moz-transform', 'rotate(' + newVal + 'deg)');
              return element.css('transform', 'rotate(' + newVal + 'deg)');
            });
          }
        };
      }
    };
  });

}).call(this);
